name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block at the workflow level
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install frontend dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Dependencies installed"
        
    - name: Debug - Pre-build directory
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents before build:"
        ls -la
        
    - name: Build frontend
      run: |
        echo "Starting build..."
        npm run build
        echo "Build completed"
        
    - name: Debug - Post-build directory
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents after build:"
        ls -la
        echo "Checking for build directory:"
        if [ -d "build" ]; then
          echo "build directory exists"
          ls -la build
        else
          echo "build directory not found"
        fi
      
#    - name: Install Shuttle CLI 
#      run: cargo install cargo-shuttle
      
    - name: Deploy to Netlify
      id: deploy  # Add an ID to reference the step
      uses: nwtgck/actions-netlify@v2
      with:
        publish-dir: 'build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
        overwrites-pull-request-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
#    - name: Deploy to Shuttle
#      run: cargo shuttle deploy --allow-dirty
#      env:
#        SHUTTLE_TOKEN: ${{ secrets.SHUTTLE_TOKEN }}

    - name: Create PR Comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const deployUrl = '${{ steps.deploy.outputs.netlify_url }}' || 'https://682c99c8944158aeb0143e6a--statuesque-biscuit-e22447.netlify.app';
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed to: ${deployUrl}`
            });
          } catch (error) {
            console.log('Failed to create PR comment:', error.message);
            // Don't fail the workflow if comment creation fails
          }