name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions block at the workflow level
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install frontend dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Dependencies installed"
        
    - name: Debug - Pre-build directory
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents before build:"
        ls -la
        
    - name: Build frontend
      run: |
        echo "Starting build..."
        npm run build
        echo "Build completed"
        
    - name: Debug - Post-build directory
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents after build:"
        ls -la
        echo "Checking for build directory:"
        if [ -d "build" ]; then
          echo "build directory exists"
          ls -la build
        else
          echo "build directory not found"
        fi
      
#    - name: Install Shuttle CLI 
#      run: cargo install cargo-shuttle
      

        
#    - name: Deploy to Shuttle
#      run: cargo shuttle deploy --allow-dirty
#      env:
#        SHUTTLE_TOKEN: ${{ secrets.SHUTTLE_TOKEN }}

  